# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='_hard_lock',
            field=models.BooleanField(db_column=b'hard_lock', default=False, editable=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='_locked_at',
            field=models.DateTimeField(db_column=b'locked_at', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='_locked_by',
            field=models.ForeignKey(db_column=b'locked_by', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_on_poll', to=settings.AUTH_USER_MODEL),
        ),
    ]
